name: docker-deploy

on:
  # Triggers the workflow on push request event but only for the "master" branch
  workflow_dispatch:
  push:
    branches: ["master"]
    paths-ignore:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Build and Push
    runs-on: ubuntu-latest

    env:
      AWS_ECR_REPO: embed-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_REPO }} .

      - name: Configure AWS Credentials for github actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}

      - name: Docker Login
        run: |
          aws ecr get-login-password \
              --region ${{ secrets.AWS_REGION }} \
          | docker login \
              --username AWS \
              --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Docker Push
        run: docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_REPO }}
